FROM python:3.8.20-slim-bullseye@sha256:e191a71397fd61fbddb6712cd43ef9a2c17df0b5e7ba67607128554cd6bff267

# Install required system packages and dependencies
RUN pip install bottle==0.12.13 cherrypy==8.9.1 wsgi-request-logger==0.4.6 prometheus_client==0.9.0

WORKDIR /
ADD _kubeless.py .

USER 1000

ENV PYTHONUNBUFFERED 1
CMD ["python", "/_kubeless.py"]
