#!/usr/bin/env bash

# Copyright (c) 2016-2017 Bitnami
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

OS_PLATFORM=${1:-linux}
OS_ARCH=${2:-arm64}

if [ -z "$3" ]; then
    TARGET="kubeless-controller-manager"
else
    TARGET=($3)
fi

if [ -z "$4" ]; then
    PKG="./cmd/http-trigger-controller/"
else
    PKG=($4)
fi

# Build kubeless-controller
GOOS=$OS_PLATFORM GOARCH=$OS_ARCH go build \
    -o="bundles/kubeless_${OS_PLATFORM}-${OS_ARCH}/$TARGET" \
    "$PKG"
